image: archlinux
repositories:
  jmr: "https://archlinux-jmr.s3.us-west-004.backblazeb2.com/$repo/$arch#55E00EDED9D418CBACB39CAD184AD86A1B97C873"
packages:
  - curl
  - git
  - pacman
  - python
  - python-argh
  - python-requests
  - python-tqdm
  - s3cmd
sources:
  - https://git.sr.ht/~jmr/pkgbuild
secrets:
  - 923d9bcd-39e8-485b-b97c-6cdd363570dd  # s3 cfg
  - 2a3e934a-190c-405f-81cd-021a78a29b1b  # sourcehut oauth token
  - 02a0c815-b30f-4ea4-ba07-c5f8f3b63fee  # PGP signing key
tasks:
  - run-orchestrator: |
      cd pkgbuild
      ./buildbot.py orchestrate
