image: archlinux
repositories:
  jmr: "https://archlinux-jmr.s3.us-west-004.backblazeb2.com/$repo/$arch#55E00EDED9D418CBACB39CAD184AD86A1B97C873"
  multilib: "http://mirror.rackspace.com/archlinux/$repo/os/$arch#c100346676634e80c940fb9e9c02ff419fecbe16"
packages:
  - curl
  - git
  - pacman
  - python
  - python-argh
  - python-requests
  - s3cmd
sources:
  - https://git.sr.ht/~jmr/pkgbuild
secrets:
  - e699b07a-a885-4022-9b4e-332d5c1b451e  # s3 cfg
  - aa330b00-43e1-4478-84ec-fa764c64cef5  # sourcehut oauth token
  - 02a0c815-b30f-4ea4-ba07-c5f8f3b63fee  # PGP signing key
tasks:
  - run-orchestrator: |
      cd pkgbuild
      ./buildbot.py orchestrate
