# Maintainer: Einhard Leichtfuß <alguien@respiranto.de>
# Contributor: Tai Chi Minh Ralph Eastwood <tcmreastwood@gmail.com>
pkgname=dict-gcide
_major_debver=0.48
_debver="${_major_debver}.5+nmu4"
pkgver=0.54
pkgrel=1
pkgdesc="GNU version of the Collaborative International Dictionary of English for dictd et al."
arch=('any')
url="https://gcide.gnu.org.ua/"
license=('GPL3')
optdepends=('dictd: dict client and server')
makedepends=('dictd' 'libmaa')
provides=('dictd-gcide')
conflicts=('dictd-gcide')
install="${pkgname}.install"
source=('fixes.sed'
        'post_webfilter.sed'
        'check.sed'
        "https://deb.debian.org/debian/pool/main/d/${pkgname}/${pkgname}_${_debver}.tar.xz"
        "https://ftp.gnu.org/gnu/gcide/gcide-${pkgver}.tar.xz"{,.sig})
sha512sums=('c62453bd7ec9fb435b357238d8dd8874b604c2470c3831882ba4331571d4fd35c7e26567c71e828dd698741c7bc87d5e0b09c2548ac27c1b6749fc17e11bff72'
            '9b87c3e0f7647f97db79c5d6ba108d2e450427a3f65d02523d1f942b2a4cce82cf7a1adc0a51ede453476a74b3c03ab861a55de61005425b3416523e4aa1290d'
            '369063665be3e8662223bd55fc7c4c87edd14ccd47fae5a586625895798cfc1c189bd3c4b3386079ff0c4c457545a48ec084630fc61b39409179c690772f2fde'
            '71134c69ece86226233c0693af1d8c776df469bbf3d4969f4a8a883061da2e23eafda2ad395648350ee3fe56f271abd20d7d3fd37c34f0401200317ed1a249be'
            '9bda8bc2e30a529bafeb3fcdd2f315025209fa2e609da707caf7b4a273221a7617a10b58d2b635e1ae980e01a790a4e09bb74ec54d6e09c9014e72b30d33b1e6'
            'SKIP')
validpgpkeys=('4BE4E62655488EB92ABB468F79FFD94BFCE230B1')


prepare()
{
	cd "$pkgname"

	sed -Ei \
		"s/\"(The Collaborative International Dictionary of English) v.${_major_debver}\"/\"\\1 v.${pkgver}\"/" \
		scan.l

	# Remove autogenerated autotools files.
	rm config.guess config.h.in config.sub configure install-sh
}


build()
{
	cd "$pkgname"

	autoreconf -fis
	./configure
	make -j1

	# Do the conversion explicitly, instead of `make db', to account for all
	# the differences to the original build process.
	# LANG=C is required so that the index file is properly sorted.
	../fixes.sed "../gcide-${pkgver}"/CIDE.? \
		| sed -f debian/sedfile \
		| ./webfilter \
		| ../post_webfilter.sed \
		| tee pre_webfmt.data \
		| LANG=C ./webfmt -c

	# `dictzip -v' neglects to print a final newline.
	dictzip -v gcide.dict
	printf '\n'
}


check()
{
	errors="$(./check.sed < "${pkgname}/pre_webfmt.data")"

	if test -n "$errors"
	then
		printf 'Errors found:\n'
		printf '%s\n' "$errors"
		return 1
	fi
}


package()
{
	install -m 0755 -d "${pkgdir}/usr/share/dictd"
	install -m 0644 -t "${pkgdir}/usr/share/dictd/" \
		"${pkgname}"/gcide.{dict.dz,index}

	install -m 0755 -d "${pkgdir}/usr/share/doc/dict-gcide"
	install -m 0644 -t "${pkgdir}/usr/share/doc/dict-gcide/" \
		"gcide-${pkgver}"/{README,INFO,pronunc.txt}
}
