name: Build Packages
on:
  push:
    branches: main
jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Container
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          tags: pkgbuild:latest
          outputs: type=docker,dest=/tmp/container.tar
      - name: Upload Container
        uses: actions/upload-artifact@v4
        with:
          name: container
          path: /tmp/container.tar
          if-no-files-found: error
          retention-days: 1
  plan-builds:
    runs-on: ubuntu-latest
    needs: build-container
    outputs:
      builds: ${{ steps.plan_builds.outputs.builds }}
    steps:
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Download Container
        uses: actions/download-artifact@v4
        with:
          name: container
          path: /tmp
      - name: Load Docker Image
        run: |
          docker load --input /tmp/container.tar
      - name: Plan Builds
        id: plan_builds
        run: |
          echo "builds=$(
          docker run pkgbuild:latest sudo -u build ./buildbot.py plan-builds
          )" >> "${GITHUB_OUTPUT}"
  build-packages:
    runs-on: ubuntu-latest
    needs: plan-builds
    name: ${{ matrix.pkgbase.pkgbase }}-${{ matrix.pkgbase.version }}
    strategy:
      matrix:
        pkgbase: ${{ fromJSON(needs.plan-builds.outputs.builds) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Python Dependencies
        run: pip install argh tqdm requests
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Download Container
        uses: actions/download-artifact@v4
        with:
          name: container
          path: /tmp
      - name: Load Docker Image
        run: |
          docker load --input /tmp/container.tar
      - name: dockerbuild
        run: ./buildbot.py dockerbuild '${{ matrix.pkgbase.subdir }}'
      - name: Upload Artifacts
        users: actions/upload-artifact@v4
        with:
          name: ${{ matrix.pkgbase.pkgbase }}-binpkgs
          path: ${{ matrix.pkgbase.artifacts_path_expr }}
          if-no-files-found: error
